name: 'Deploy Client'
description: 'Deploy Client'

inputs:
  project:
    description: 'Project'
    required: true
  app:
    description: 'App'
    required: true
  env:
    description: 'Environment'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Get cloudfront distribution infos of s3 bucket
      id: distribution-infos
      env:
        BUCKET_NAME: ${{ inputs.project }}-${{ inputs.app }}-${{ inputs.env }}
      shell: bash
      run: |
        echo "bucket-name=$BUCKET_NAME" >> $GITHUB_OUTPUT
        echo "id=$(aws cloudfront list-distributions --query "DistributionList.Items[*].{id:Id,origin:Origins.Items[0].Id}[?origin=='$BUCKET_NAME'].id" --output text)" >> $GITHUB_OUTPUT
    - name: Upload to s3 and invalidate cloudfront distribution
      shell: bash
      run: |
        aws s3 sync ./dist/apps/${{ inputs.app }} s3://${{ steps.distribution-infos.outputs.bucket-name }} --delete
        aws cloudfront create-invalidation --distribution-id ${{ steps.distribution-infos.outputs.id }} --paths "/index.html"
