name: 'Deploy ECS Task'
description: 'Deploy ECS Task'

inputs:
  image:
    description: 'Docker image'
    required: true
  task-definition-family:
    description: 'ECS task definition family'
    required: true
  cluster:
    description: 'ECS cluster'
    required: true
  service:
    description: 'ECS service'
    required: true
  container-name:
    description: 'ECS container name'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Download task definition
      shell: bash
      run: |
        aws ecs describe-task-definition --task-definition ${{ inputs.task-definition-family }} --query taskDefinition > task-definition.json
        cat task-definition.json
    - name: Fill in the new image ID in the Amazon ECS task definition
      id: task-def
      uses: aws-actions/amazon-ecs-render-task-definition@v1
      with:
        task-definition: task-definition.json
        container-name: ${{ inputs.container-name }}
        image: ${{ inputs.image }}
    - name: Deploy Amazon ECS task definition
      uses: aws-actions/amazon-ecs-deploy-task-definition@v1
      with:
        task-definition: ${{ steps.task-def.outputs.task-definition }}
        service: ${{ inputs.service }}
        cluster: ${{ inputs.cluster }}
        wait-for-service-stability: true
