name: Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

env:
  NODE_VERSION: 16.17.0
  PNPM_VERSION: 7.13.6
  ENV: dev

jobs:
  deploy:
    uses: .github/workflows/deploy-base.yml
    with:
      node-version: ${{ env.NODE_VERSION }}
      pnpm-version: ${{ env.PNPM_VERSION }}
      branch-name: main
      env: ${{ env.ENV }}
    secrets: inherit
