name: Deploy Dev

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

jobs:
  deploy-dev:
    uses: ./.github/workflows/deploy-base.yml
    with:
      branch-name: main
      env: dev
    secrets: inherit
