name: Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    uses: ./.github/workflows/deploy-base.yml
    with:
      node-version: 16.17.0
      pnpm-version: 7.13.6
      branch-name: main
      env: dev
    secrets: inherit
